import NavBar from "./components/Navbar";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="bg-white dark:bg-[#111010] flex min-h-screen flex-col items-center justify-between">
        <main>
          <NavBar />
          {children}
        </main>
      </body>
    </html>
  );
}
